#!/usr/bin/bash

# Name of the private key
PRIVATE_KEY_NAME="school"

# Number of bits in the key
BITS=4096

# Passphrase
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $BITS -f $PRIVATE_KEY_NAME -q -N $PASSPHRASE

# Output success message
echo "RSA key pair generated successfully."
